import Navbar from "@/components/Navbar"

import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { QueryWrapper } from "@/components/Query/QueryWrapper"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <QueryWrapper>{children}</QueryWrapper>
      </body>
    </html>
  )
}
